### ISSUE TITLE
The measure of the experiment

### ISSUE THREAD

**Issue by TheGreatLy** [rraileanu/idaac#1]
Hello, i have a question, What does 'The mean and standard deviation are computed using 10
runs with different seeds.' mean  in Table 4?  The seeds means ten levels seeds or the random seed that determines network initialization? thank you.

**Comment by rraileanu** [comment]
In that sentence, the seed refers to the model seed, meaning that you train 10 different models (using the same set-up) and compute the mean over those. To compute the results for one of the seeds, we use 100 different levels sampled from the entire distribution of levels for that particular game (i.e. https://github.com/rraileanu/idaac/blob/main/test.py#L18) after training for 25M steps on the first 200 levels.
