### ISSUE TITLE
Reproducing DAAC results on Procgen Miner

### ISSUE THREAD

**Issue by MarcoMeter** [rraileanu/idaac#2]
Hi @rraileanu 

thanks for your scientific contributions!

I'm currently trying to reproduce your Miner results. After installing the dependencies, I simply run `python train.py --env_name miner --algo daac` to launch the training. My first run ended up pretty bad, not even near your reported score.

Here is the log of that training run.
[daac.log](https://github.com/rraileanu/idaac/files/7259797/daac.log)

To verify that this is not just an extreme outlier, I got two more training runs running, which are at 12.5 million steps right now, but behave similar so far.

Did I miss something or how can I reproduce the results of your paper? I added DAAC to my custom PPO implementation and was struggling to get good results either.

**Comment by rraileanu** [comment]
For Miner, you should use the flag `--use_best_hps` to obtain the results shown in the paper. There is a set of HPs that works best across all games (which is the default one in the codebase), however there are a few games which are more difficult to tune and require different values for some of the HPs in order to get the best results and reproduce the numbers reported in the paper. 

I hope this fixes the issue but please let me know in case you are still not able to reproduce the results for Miner!

**Comment by MarcoMeter** [comment]
Thanks, I'll try the flag now.

**Comment by MarcoMeter** [comment]
[daac_best_0.log](https://github.com/rraileanu/idaac/files/7260983/daac_best_0.log)
[daac_best_1.log](https://github.com/rraileanu/idaac/files/7260984/daac_best_1.log)

These are two runs using the `--use_best_hps` flag. The results seem to have quite a high variance.

**Comment by rraileanu** [comment]
Yes, I remember this being an issue with my runs as well. This is why the results are reported over 10 seeds, which I recommend as the minimum. Check out this paper https://arxiv.org/pdf/2108.13264.pdf for more robust metrics which should also hold for fewer seeds.

**Comment by MarcoMeter** [comment]
Indeed!

Have you tried DAAC on other environments than Procgen? I'm wondering if there is another environment that shows DAAC's superior performance, but trains faster. 

Or which of the procgen environments is the most reliable one in your opinion?

**Comment by rraileanu** [comment]
I've only tried it on DMC with distractors but I don't think it's a particularly good environment for DAAC and it was quite difficult to tune it on DMC. I think something more similar to DMLab, MiniHack or MiniGrid might be reasonable environments to try this on. In particular, MiniHack and MiniGrid are quite fast to run and you can easily create your own tasks to probe different abilities, but they don't use visual inputs. DMLab is the type of environment where I would expect DAAC to work well but it is slower to run.

**Comment by MarcoMeter** [comment]
Minigrid can be easily rendered using `env.get_obs_render(obs["image"], tile_size=28)`

It also looks like that I can reproduce your training results with my custom code base now.
[daac_miner_1.log](https://github.com/rraileanu/idaac/files/7264599/daac_miner_1.log)
[daac_miner_0.log](https://github.com/rraileanu/idaac/files/7264600/daac_miner_0.log)

Thanks for the helpful chat.
