### ISSUE TITLE
About adversarial training

### ISSUE THREAD

**Issue by Asuka20** [rraileanu/idaac#3]
Hi, in Section 4.3 the paper says " ... only the encoder’s parameters are updated by **minimizing** the loss in eq. 3", but the eq. 3 is exactly the entropy (of the discriminator regarding which observation was first in the episode), which should be **maximized** according to the paper. Did I misunderstand somewhere?

**Comment by rraileanu** [comment]
Yes you are right, that is a typo. Thanks for pointing it out!
